# Generated by Django 4.0.4 on 2022-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
